# Generated by Django 3.0.8 on 2020-07-28 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('ambientes', models.CharField(max_length=200)),
                ('cantidad_ambientes', models.CharField(max_length=20)),
                ('servicios', models.CharField(max_length=200)),
                ('max_personas', models.IntegerField()),
                ('precio_dia', models.FloatField()),
                ('reservado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id_blog', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('comentarios', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizar',
            fields=[
                ('id_cotizar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.IntegerField()),
                ('opciones', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.CharField(max_length=500)),
                ('vision', models.CharField(max_length=500)),
                ('descripcion_blog', models.CharField(max_length=500)),
                ('nombre_logo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_imagen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.IntegerField(primary_key=True, serialize=False)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('nombre_ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubImagenes',
            fields=[
                ('id_sub_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_imagen', models.CharField(max_length=50)),
                ('id_imagen', models.ForeignKey(db_column='id_imagen', on_delete=django.db.models.deletion.DO_NOTHING, to='admins.Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('n_adultos', models.IntegerField()),
                ('n_ninos', models.IntegerField(blank=True, null=True)),
                ('n_dias', models.IntegerField()),
                ('precio_total', models.FloatField()),
                ('id_anuncio', models.ForeignKey(db_column='id_anuncio', on_delete=django.db.models.deletion.DO_NOTHING, to='admins.Anuncios')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('fecha_maxima', models.DateField()),
                ('precio_oferta', models.FloatField()),
                ('id_anuncio', models.ForeignKey(db_column='id_anuncio', on_delete=django.db.models.deletion.DO_NOTHING, to='admins.Anuncios')),
            ],
        ),
        migrations.AddField(
            model_name='anuncios',
            name='id_imagen',
            field=models.ForeignKey(db_column='id_imagen', on_delete=django.db.models.deletion.DO_NOTHING, to='admins.Imagen'),
        ),
        migrations.AddField(
            model_name='anuncios',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='admins.Tipo'),
        ),
        migrations.AddField(
            model_name='anuncios',
            name='id_ubicacion',
            field=models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='admins.Ubicacion'),
        ),
    ]
