# Generated by Django 3.0.8 on 2020-08-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre_imagen',
            field=models.ImageField(upload_to='admins/photos'),
        ),
        migrations.AlterField(
            model_name='subimagenes',
            name='nombre_imagen',
            field=models.ImageField(upload_to='admins/photos'),
        ),
    ]
