# Generated by Django 3.0.8 on 2020-07-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='fecha_maxima',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='anuncios',
            name='oferta',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='anuncios',
            name='precio_oferta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='anuncios',
            name='reservado',
            field=models.BooleanField(),
        ),
    ]
