# Generated by Django 3.0.8 on 2020-07-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('celular', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=800)),
            ],
        ),
    ]
