# Generated by Django 3.0.8 on 2020-07-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20200730_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='fecha_maxima',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anuncios',
            name='precio_oferta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
